openapi: 3.0.0
info:
  title: Corporate number system API v4
  description: Corporate number system API v4
  termsOfService: 'https://www.houjin-bangou.nta.go.jp/webapi/riyokiyaku.html'
  contact:
    name: Contact Information
    url: 'https://www.houjin-bangou.nta.go.jp/webapi/toiawase/'
  version: 1.0.3
servers:
  - url: 'https://api.houjin-bangou.nta.go.jp/4'
tags:
  - name: corporations
paths:
  /name:
    get:
      summary: 法人名を指定しリクエストすることで、指定した法人名の基本３情報及び付随する情報を取得することができます。
      operationId: GetCorporations
      description: 法人名による法人情報の取得
      parameters:
        - name: name
          in: query
          description: |-
            取得の対象とする法人名を
            URL エンコード（UTF-8）した値をセットします。
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/mode'
        - $ref: '#/components/parameters/target'
        - $ref: '#/components/parameters/address'
        - $ref: '#/components/parameters/kind'
        - $ref: '#/components/parameters/change'
        - $ref: '#/components/parameters/close'
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/divide'
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: ./responses/ResponseWrapper.v1.yaml
        '400':
          $ref: '#/components/responses/Error400'
        '403':
          $ref: '#/components/responses/Error403'
        '404':
          $ref: '#/components/responses/Error404'
        '500':
          $ref: '#/components/responses/Error500'
      tags:
        - corporations
components:
  securitySchemes:
    id:
      name: id
      description: 国税庁に申請して取得した認証用のアプリケーションIDです。
      type: apiKey
      in: query
  schemas:
    ProcessCodeType:
      $ref: ./types/ProcessCodeType.v1.yaml
    CorrectCodeType:
      $ref: ./types/CorrectCodeType.v1.yaml
    CorporateType:
      $ref: ./types/CorporateType.v1.yaml
    PrefectureType:
      $ref: ./types/PrefectureType.v1.yaml
    Corporation:
      $ref: ./models/Corporation.v1.yaml
  parameters:
    type:
      name: type
      description: リクエストに対して応答するデータのファイル形式と文字コードを指定します。
      in: query
      schema:
        type: string
        enum:
          - '12'
          - '01'
          - '02'
        default: '12'
        example: '12'
      required: true
    mode:
      name: mode
      description: |-
        検索方式を指定できます。
        指定しない場合は、｢１｣（前方一致検索）で処理します。
      in: query
      required: false
      schema:
        type: integer
        enum:
          - 1
          - 2
        default: 1
    target:
      name: target
      description: |-
        検索対象を指定できます。
        指定しない場合は、｢１｣（JIS 第一・第二水準）で処理します。
      in: query
      required: false
      schema:
        type: integer
        enum:
          - 1
          - 2
          - 3
        default: 1
    address:
      name: address
      description: |-
        国内所在地の都道府県コード又は
        都道府県コードと市区町村コードを組み合わせたコードのいずれかを指定できます。
        市区町村コードのみではエラー(エラーコード 051)となります。
      in: query
      required: false
      schema:
        type: string
        pattern: '[0-9]{2,5}'
    kind:
      name: kind
      description: 法人種別を指定できます。
      in: query
      required: false
      schema:
        type: string
        enum:
          - '01'
          - '02'
          - '03'
          - '04'
    change:
      name: change
      description: |-
        法人名や所在地の変更があった法人等に
        ついて過去の情報を含めて検索するかどうかを指定できます。
      in: query
      required: false
      schema:
        type: integer
        enum:
          - 0
          - 1
        default: 0
    close:
      name: close
      description: 登記記録の閉鎖等があった法人等の情報を取得するかどうかを指定できます。
      in: query
      required: false
      schema:
        type: integer
        enum:
          - 0
          - 1
        default: 1
    from:
      name: from
      description: 取得の対象とする法人番号指定年月日の開始日を指定できます。
      in: query
      required: false
      schema:
        type: string
        pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}'
    to:
      name: to
      description: '取得の対象とする法人番号指定年月日の終了日を指定できます。 '
      in: query
      required: false
      schema:
        type: string
        pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}'
    divide:
      name: divide
      description: |-
        分割番号を指定できます。
        指定しない場合は、「１」で処理します。
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 99999
  responses:
    Error400:
      description: error codes when http response 400 is returned
      content:
        application/json:
          schema:
            type: string
            enum:
              - '010'
              - '011'
              - '012'
              - '013'
              - '020'
              - '021'
              - '022'
              - '030'
              - '031'
              - '040'
              - '041'
              - '042'
              - '043'
              - '050'
              - '051'
              - '052'
              - '060'
              - '061'
              - '062'
              - '063'
              - '070'
              - '071'
              - '072'
              - '073'
              - '080'
              - '081'
              - '082'
              - '090'
              - '100'
              - '101'
              - '102'
              - '103'
              - '110'
              - '111'
              - '112'
              - '120'
              - '121'
              - '122'
              - '130'
              - '131'
              - '132'
              - '140'
              - '141'
              - '142'
              - '150'
              - '151'
              - '152'
              - '160'
              - '161'
              - '170'
              - '180'
    Error403:
      description: |-
        同一アプリケーションＩＤを用い、一定期間内に多数のアクセスをした結果アク
        セス制限された後に、当該ＩＤを利用しアクセスした場合に設定されます。
      content:
        application/json:
          schema:
            type: string
    Error404:
      description: |-
        指定されたアプリケーションIDが登録されていない又は無効の場合等に設定
        されます。
      content:
        application/json:
          schema:
            type: string
    Error500:
      description: 法人番号公表機能に障害等が発生した場合に設定されます。
      content:
        application/json:
          schema:
            type: string
security:
  - id: []
